[versions]
micronaut = '3.8.2'
jline = '3.21.0'

# Gradle plugins
micronaut-gradle-plugin = "3.7.0"
kotlin-gradle-plugin = "1.9.10"

[libraries]
jline-graal = { module = "org.jline:jline-graal", version.ref = 'jline' }
jline-terminal-jansi = { module = "org.jline:jline-terminal-jansi", version.ref = 'jline' }
jline-terminal-jna = { module = "org.jline:jline-terminal-jna", version.ref = 'jline' }

micronaut-http-client = { module = "io.micronaut:micronaut-http-client" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson" }
micronaut-reactor = { module = "io.micronaut.reactor:micronaut-reactor" }

# Plugins
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
gradle-kotlin-allopen = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin-gradle-plugin" }